[project]
name = "day-play"
version = "0.1.0"
description = "Personal project for gamified task management and FastAPI learning - A RESTful API for daily task management built with FastAPI, SQLModel, and SQLite"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.2",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.5",
    "sqlmodel>=0.0.27",
    "telegram>=0.0.1",
    "uvicorn>=0.37.0",
]
